### ISSUE TITLE
Save credentials as an (encrypted) file

### ISSUE THREAD

**Issue by MrEliptik** [MrEliptik/godot_stream_overlays#6]
In the Twitch login panel, add a button to save the credentials in a file. 

The file could be encrypted for example with [File.open_encrypted()](https://docs.godotengine.org/fr/stable/classes/class_file.html#class-file-method-open-encrypted) or using the [Crypto class](https://docs.godotengine.org/fr/stable/classes/class_crypto.html).

**Comment by CptFubar** [comment]
Hey, i already finished the implementation of a credentials manager. #8 
The implementation features a custom resource class (CredentialsManager) that handles the storage and encryption
of all locally stored oauth tokens.
